name: Feature Request
description: Suggest a new feature or component for ZeroZeeker
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Got a feature idea? Excellent. We genuinely want to hear it. Fill out this form and let us know what would make ZeroZeeker better for you.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Help us understand your pain point.
      placeholder: Currently, when I try to do X, I run into Y problem because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or improvement you are envisioning. Be as detailed as you like.
      placeholder: I would like a feature that allows me to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you tried any workarounds or considered other approaches? Knowing what you have already tried helps us understand the full picture.

  - type: dropdown
    id: component-type
    attributes:
      label: Component Type
      description: What category does your feature request fall into?
      options:
        - UI Component
        - Layout Component
        - Utility Function
        - CLI Feature
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: effort
    attributes:
      label: Contribution
      description: Interested in building this yourself? We love contributors.
      options:
        - label: I am willing to implement this feature myself

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, screenshots, code examples, or additional information that would help us understand your request better
